name: cw_zcash
description: Zcash library for cake wallet
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  warp_api:
    path: ../scripts/zcash_lib/packages/warp_api_ffi
  cw_core:
    path: ../cw_core
  mobx: ^2.5.0
  bip39: ^1.0.6
  mutex: ^3.1.0

  path: any
  flat_buffers: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  build_resolvers: ^2.4.4
  mobx_codegen: ^2.0.7
  hive_generator: ^2.0.1
  ffigen: ^16.1.0
