name: cake_wallet
description: Cake Wallet.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.0.8+18

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  intl: ^0.16.0
  url_launcher: ^5.1.2
  qr: ^1.2.0
  uuid: 2.0.1
  shared_preferences: ^0.5.3+4
  flutter_secure_storage:
    git:
      url: https://github.com/cake-tech/flutter_secure_storage.git
      ref: cake
      version: 3.3.57
  provider: ^3.1.0
  rxdart: ^0.22.2
  yaml: ^2.1.16
  barcode_scan: any
  http: ^0.12.0+2
  path_provider: ^1.3.0
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  flutter_slidable: ^0.5.3
  share: ^0.6.2+1
  esys_flutter_share: ^1.0.2
  date_range_picker: ^1.0.6
  dio: 3.0.7
  cw_monero:
    path: ./cw_monero
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  local_auth: ^0.6.1
  package_info: ^0.4.0+13
  devicelocale: ^0.2.1
  auto_size_text: ^2.1.0
  dotted_border: ^1.0.5
  smooth_page_indicator: ^0.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  encrypt: ^4.0.0
  password: ^1.0.0
  basic_utils: ^1.0.8
  bitcoin_flutter: ^2.0.0
  get_it: ^4.0.2
  connectivity: ^0.4.9+2
  keyboard_actions: ^3.3.0
  flushbar: ^1.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.3
  build_resolvers: ^1.3.10
  mobx_codegen: ^1.1.0+1
  hive_generator: ^0.8.1
  flutter_launcher_icons: ^0.7.4
  pedantic: ^1.8.0

flutter_icons:
  image_path: "assets/images/app_logo.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/node_list.yml
    - assets/electrum_server_list.yml
    - assets/text/
    - assets/faq/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Medium.ttf
        - asset: assets/fonts/Lato-SemiBold.ttf
        - asset: assets/fonts/Lato-Bold.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages