name: cw_core
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: https://cakewallet.com

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  file: ^7.0.0
  path_provider: ^2.1.5
  mobx: ^2.0.7+4
  flutter_mobx: ^2.0.6+1
  intl: any
  encrypt: ^5.0.1
  decimal: ^2.3.3
  cake_backup:
    git:
      url: https://github.com/cake-tech/cake_backup.git
      ref: main
      version: 1.0.0
  socks5_proxy:
    git:
      url: https://github.com/LacticWhale/socks_dart
      ref: 27ad7c2efae8d7460325c74b90f660085cbd0685
  unorm_dart: ^0.3.0
  on_chain:
    git:
      url: https://github.com/cake-tech/on_chain.git
      ref: cake-update-v2
  socks_socket:
    git:
      url: https://github.com/sneurlax/socks_socket
      ref: e6232c53c1595469931ababa878759a067c02e94
  torch_dart:
    path: ../scripts/torch_dart
  blockchain_utils:
    git:
      url: https://github.com/cake-tech/blockchain_utils
      ref: cake-update-v2
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.3.4+4
  bech32:
    git:
      url: https://github.com/cake-tech/bech32.git
  sqlite3_flutter_libs: 0.5.40

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  build_resolvers: ^2.4.4
  mobx_codegen: ^2.0.7
  hive_generator: ^2.0.1

dependency_overrides:
  watcher: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
