name: cw_evm
description: A new Flutter package project.
version: 0.0.1
publish_to: none
author: Cake Wallet
homepage: https://cakewallet.com

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.7.1
  eth_sig_util: ^0.0.9
  erc20: ^1.0.1
  bip39: ^1.0.6
  bip32: ^2.0.0
  hex: ^0.2.0
  http: ^1.1.0
  hive: ^2.2.3
  collection: ^1.17.1
  shared_preferences: ^2.0.15
  mobx: ^2.0.7+4
  cw_core:
    path: ../cw_core
  ledger_flutter_plus: ^1.4.1
  ledger_ethereum:
    git:
      url: https://github.com/cake-tech/ledger-flutter-plus-plugins
      path: packages/ledger-ethereum
      ref: f4761cd5171d4c1e2e42fd3298261650539fb2db
  bitbox_flutter:
    path: ../scripts/bitbox_flutter
  trezor_connect:
    git:
      url: https://github.com/cake-tech/trezor_connect
      ref: 59b3ceec158d3393b20d0c596cab2abcc62ac8e4

dependency_overrides:
  web3dart:
    git:
      url: https://github.com/cake-tech/web3dart.git
      ref: cake
  watcher: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  mobx_codegen: ^2.0.7
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
