blank_issues_enabled: false
contact_links:
  - name: Feature or Enhancement Request âœ¨
    url: https://github.com/cake-tech/cake_wallet/discussions/new?category=feature-requests
    about: Suggest an idea for Cake Wallet
  - name: Not sure where to start?
    url: https://docs.cakewallet.com
    about: Start by reading checking out the guides!
  - name: Need help?
    url: https://cakewallet.com/#contact
    about: Use our live chat or send a support email!
