name: cw_monero
version: 0.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.cakewallet.monero
        pluginClass: CwMoneroPlugin
      ios:
        pluginClass: CwMoneroPlugin