name: cw_solana
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: https://cakewallet.com

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cw_core:
    path: ../cw_core
  http: ^1.1.0
  hive: ^2.2.3
  bip39: ^1.0.6
  mobx: ^2.3.0+1
  shared_preferences: ^2.0.15
  bip32: ^2.0.0
  hex: ^0.2.0
  on_chain:
    git:
      url: https://github.com/cake-tech/on_chain.git
      ref: cake-update-v2
  blockchain_utils:
    git:
      url: https://github.com/cake-tech/blockchain_utils
      ref: cake-update-v2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  mobx_codegen: ^2.0.7
  hive_generator: ^1.1.3

dependency_overrides:
  watcher: ^1.1.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
