name: cw_bitcoin_cash
description: A new Flutter package project.
version: 0.0.1
publish_to: none
author: Cake Wallet
homepage: https://cakewallet.com

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bip39: ^1.0.6
  bip32: ^2.0.0
  path_provider: ^2.0.11
  mobx: ^2.0.7+4
  flutter_mobx: ^2.0.6+1
  cw_core:
    path: ../cw_core
  cw_bitcoin:
    path: ../cw_bitcoin
  bitbox:
    git:
      url: https://github.com/cake-tech/bitbox-flutter.git
      ref: Add-Support-For-OP-Return-data
  blockchain_utils:
    git:
      url: https://github.com/cake-tech/blockchain_utils
      ref: cake-update-v2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  mobx_codegen: ^2.0.7
  hive_generator: ^2.0.1

dependency_overrides:
  watcher: ^1.1.0
  bitcoin_base:
    git:
      url: https://github.com/cake-tech/bitcoin_base
      ref: cake-update-v5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#

