name: cw_tron
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: https://cakewallet.com

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cw_core:
    path: ../cw_core
  cw_evm:
    path: ../cw_evm
  on_chain:
    git:
      url: https://github.com/cake-tech/on_chain.git
      ref: cake-update-v4
  blockchain_utils:
    git:
      url: https://github.com/cake-tech/blockchain_utils
      ref: cake-update-v4
  mobx: ^2.3.0+1
  bip39: ^1.0.6
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  hive_generator: ^1.1.3

dependency_overrides:
  blockchain_utils:
    git:
      url: https://github.com/cake-tech/blockchain_utils
      ref: cake-update-v4

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
