name: cw_ethereum
description: A new Flutter package project.
version: 0.0.1
publish_to: none
author: Cake Wallet
homepage: https://cakewallet.com

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.7.1
  cw_core:
    path: ../cw_core
  cw_evm:
    path: ../cw_evm
  hive: ^2.2.3

dependency_overrides:
  web3dart:
    git:
      url: https://github.com/cake-tech/web3dart.git
      ref: cake
  watcher: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
