name: cw_bitcoin
description: A new Flutter package project.
version: 0.0.1
publish_to: none
author: Cake Wallet
homepage: https://cakewallet.com

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  http: ^1.1.0
  mobx: ^2.0.7+4
  flutter_mobx: ^2.0.6+1
  intl: ^0.19.0
  shared_preferences: ^2.0.15
  cw_core:
    path: ../cw_core
  bitbox:
    git:
      url: https://github.com/cake-tech/bitbox-flutter.git
      ref: Add-Support-For-OP-Return-data
  rxdart: ^0.28.0
  cryptography: ^2.0.5
  blockchain_utils:
    git:
      url: https://github.com/cake-tech/blockchain_utils
      ref: cake-update-v2
  cw_mweb:
    path: ../cw_mweb
  grpc: ^4.0.1
  sp_scanner:
    git:
      url: https://github.com/cake-tech/sp_scanner
      ref: sp_v4.0.0
  bech32:
    git:
      url: https://github.com/cake-tech/bech32.git
  payjoin_flutter:
    git:
      url: https://github.com/OmarHatem28/payjoin-flutter
      ref: da83a23f3a011cb49eb3b6513cd485b3fb8867ff #cake-v2
  ledger_flutter_plus: ^1.4.1
  ledger_bitcoin:
    git:
      url: https://github.com/cake-tech/ledger-flutter-plus-plugins
      path: packages/ledger-bitcoin
      ref: trunk
  ledger_litecoin:
    git:
      url: https://github.com/cake-tech/ledger-flutter-plus-plugins
      path: packages/ledger-litecoin
  socks_socket:
    git:
      url: https://github.com/sneurlax/socks_socket
      ref: e6232c53c1595469931ababa878759a067c02e94
  ur:
    git:
      url: https://github.com/bukata-sa/bc-ur-dart
      ref: 5738f70d0ec3d50977ac3dd01fed62939600238b

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  build_resolvers: ^2.4.4
  mobx_codegen: ^2.0.7
  hive_generator: ^2.0.1

dependency_overrides:
  watcher: ^1.1.0
  protobuf: ^3.1.0
  bitcoin_base:
    git:
      url: https://github.com/cake-tech/bitcoin_base
      ref: cake-update-v10
  pointycastle: 3.7.4
  ffi: 2.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
