name: Automated Integration Tests

on: 
  pull_request:
    branches:
      [main]

jobs: 
  Automated_integration_tests:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          api-level: [23, 24, 29]

    steps:
      - name: ğŸ¤ŒğŸ¼ Checkout
        uses: actions/checkout@v4

      - name: ğŸ¦¾ Use JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: "11.x"
      
      - name: ğŸ¦¾ Use Flutter 3.19.6
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.19.6"
          channel: stable

      - name: ğŸ¦¾ Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: ğŸ¦¾ Cache gradle
        uses: gradle/actions/setup-gradle@v3
          
      - name: ğŸ¦¾ Cache AVD
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
              ~/.android/avd/*
              ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: ğŸ¦¾ Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: ğŸš€ Integration tests on Android Emualator
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: flutter test integration_test